### ISSUE TITLE
Error: StyleSheetRegistry: styleId: `jsx-2731718379` not found.

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#140]
Steps to reproduce:
- Mac, Chrome Canary
- Setup fund
- After finish of setup in the redirect or so

Funny is: If I refresh and try again it works. But I had the same error twice.

<img width="1552" alt="screen shot 2018-07-11 at 16 21 14" src="https://user-images.githubusercontent.com/103280/42578296-86177020-8526-11e8-8a2c-04dd6f2812b3.png">

```
_app.js:1 👋🤓
_app.js:1 Hello nerd. Checking out the internals of the ipfs-frontend? We like that! If you want to work with us, send us a message: team@melonport.com.
main-7a452c3c1694ab4a9dee.js:1 Error: StyleSheetRegistry: styleId: `jsx-2731718379` not found.
    at p (index.js:1)
    at e (index.js:1)
    at t.e (index.js:1)
    at Zi (main-7a452c3c1694ab4a9dee.js:1)
    at eo (main-7a452c3c1694ab4a9dee.js:1)
    at ss (main-7a452c3c1694ab4a9dee.js:1)
    at os (main-7a452c3c1694ab4a9dee.js:1)
    at ns (main-7a452c3c1694ab4a9dee.js:1)
    at rs (main-7a452c3c1694ab4a9dee.js:1)
    at Xo (main-7a452c3c1694ab4a9dee.js:1)
Yi @ main-7a452c3c1694ab4a9dee.js:1
main-7a452c3c1694ab4a9dee.js:1 StyleSheetRegistry: styleId: `jsx-2731718379` not found.
Error: StyleSheetRegistry: styleId: `jsx-2731718379` not found.
    at p (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/62c8b141-d658-4d4f-869b-fdc408f78151/page/index.js:1:120878)
    at e (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/62c8b141-d658-4d4f-869b-fdc408f78151/page/index.js:1:118912)
    at t.e (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/62c8b141-d658-4d4f-869b-fdc408f78151/page/index.js:1:116258)
    at Zi (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:863106)
    at eo (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:864667)
    at ss (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:873931)
    at os (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:871825)
    at ns (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:871306)
    at rs (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:871132)
    at Xo (https://ipfs.io/ipfs/Qmec8xZH6qZaf4PyDEkoAhPk3asT9MXSPLuGMdSzKK15nR/_next/static/commons/main-7a452c3c1694ab4a9dee.js:1:870500)


    in t
    in form
    in E
    in div
    in Z
    in t
    in t
    in i
    in div
    in div
    in div
    in e
    in Connect(e)
    in div
    in Ks
    in div
    in e
    in Connect(e)
    in t
    in App
    in t
    in WithApollo(App)
    in r
    in n
e @ main-7a452c3c1694ab4a9dee.js:1

```

**Comment by jennazenk** [comment]
Had the same error twice on deployed version. Can't reproduce locally

**Comment by jennazenk** [comment]
any idea @fubhy @gempi ?

**Comment by fubhy** [comment]
Fixed.
