### ISSUE TITLE
Fix "yarn install"/"yarn bootstrap"

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon-lab#53]
I had to remove the following line:
```
"postinstall": "electron-builder install-app-deps",
```

from `manager-interface/package.json` in order to get `yarn install` working again.

Here is the relevant log:

```bash
$ yarn bootstrap
yarn run v1.7.0
$ lerna bootstrap
lerna info version 2.10.2
lerna info versioning independent
lerna info Bootstrapping 20 packages
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn install --mutex network:42424 --non-interactive
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "@babel/core@^7.0.0 || ^7.0.0-rc || ^7.0.0-beta.32".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "webpack@>=2".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmet peer dependency "babel-runtime@>=6.0.0".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
lerna ERR! warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
lerna ERR! error /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface: Command failed.
lerna ERR! Exit code: 127
lerna ERR! Command: electron-builder install-app-deps
lerna ERR! Arguments:
lerna ERR! Directory: /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface
lerna ERR! Output:
lerna ERR! /bin/sh: electron-builder: command not found
lerna ERR! [1/4] Resolving packages...
lerna ERR! [2/4] Fetching packages...
lerna ERR! info 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible with this module.
lerna ERR! info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
lerna ERR! info 7zip-bin-win@2.2.0: The platform "darwin" is incompatible with this module.
lerna ERR! info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
lerna ERR! [3/4] Linking dependencies...
lerna ERR! [4/4] Building fresh packages...
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/Users/schmidsi/Development/@melonproject/melon-lab/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: yarn install --mutex network:42424 --non-interactive
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "@babel/core@^7.0.0 || ^7.0.0-rc || ^7.0.0-beta.32".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "webpack@>=2".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmetpeer dependency "babel-core@^6.26.0 || ^7.0.0-0".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmetpeer dependency "babel-runtime@>=6.0.0".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise@4.2.2" has unmet peer dependency "request@^2.34".
warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".
error /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface: Command failed.
Exit code: 127
Command: electron-builder install-app-deps
Arguments:
Directory: /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface
Output:
/bin/sh: electron-builder: command not found
[1/4] Resolving packages...
[2/4] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.2.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (/Users/schmidsi/Development/@melonproject/melon-lab/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '[1/4] Resolving packages...\n[2/4] Fetching packages...\ninfo 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible withthis module.\ninfo "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.\ninfo7zip-bin-win@2.2.0: The platform "darwin" is incompatible with this module.\ninfo "7zip-bin-win@2.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.\n[3/4] Linking dependencies...\n[4/4] Building fresh packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr: 'warning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "@babel/core@^7.0.0 || ^7.0.0-rc || ^7.0.0-beta.32".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/faucet > babel-loader@8.0.0-beta.2" has unmet peer dependency "webpack@>=2".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmet peer dependency "babel-core@^6.26.0 || ^7.0.0-0".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/manager-components > @storybook/react@3.4.5" has unmet peer dependency "babel-runtime@>=6.0.0".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise@4.2.2" has unmet peer dependency "request@^2.34".\nwarning "workspace-aggregator-7fc22d2a-c31a-49d9-a06e-b668953e3215 > @melonproject/exchange-aggregator > @melonproject/smart-contracts > request-promise > request-promise-core@1.1.1" has unmet peer dependency "request@^2.34".\nerror /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface: Command failed.\nExit code: 127\nCommand: electron-builder install-app-deps\nArguments: \nDirectory: /Users/schmidsi/Development/@melonproject/melon-lab/node_modules/melonproject-manager-interface\nOutput:\n/bin/sh: electron-builder: command not found\n',
  failed: true,
  signal: null,
  cmd: 'yarn install --mutex network:42424 --non-interactive',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fubhy** [comment]
I replaced the fork of electron-builder with the updated package.

**Comment by schmidsi** [comment]
Works for me. Thanks.
